### ISSUE TITLE
MVP tracking issue

### ISSUE THREAD

**Issue by negasora** [decompiler-explorer/decompiler-explorer#1]
General architecture:
- [x] Frontend (nginx?)
- [x] Middle (glennbolt?)
- [x] Backend (all the decompilers)

MVP:
- [x] binary upload
- [x] Binja/Ghida/Angr output
- [x] resource limits (filesize client/server limits and runtime server limits)
- [x] rate limiting of some kind
- [x] separate frontend/backend
- [x] traefik/HTTPS
- [x] cached/static render
- [x] S3 storage
- [x] authenticated api
- [x] Don't use printing but rather return value from wrapper (change structure of back-ends)
- [x] Syntax highlight apps that don't have it built-in
- [x] Make go pretty (theme HTML)
- [x] Comment out version info at top of file  and normalize text for each decompiler
- [x] Add readme
- [x] Escape non-html output

POST MVP:
- [ ] S3 logins for friendlies
- [ ] some threat modeling/dealing with eventuality of being popped
- [ ] Support for uploading source and/or selecting a function?
